<?php

/**
 * QMS – F-09 Stage 1 Audit Report
 * Template for displaying Stage 1 audit findings and observations
 * ACF Group: group_68850e57b5024
 */

if (!defined('ABSPATH')) exit;

function qms09_field($key, $post_id) {
    $val = get_field($key, $post_id);
    return !empty($val) ? $val : '-';
}

// Fetch ACF fields
$org_name           = qms09_field('organization_name', $post_id);
$ref_no             = qms09_field('ref_no', $post_id);
$audit_date         = qms09_field('audit_date', $post_id);
$audit_team         = qms09_field('audit_team_members', $post_id);
$findings           = qms09_field('audit_findings', $post_id);
$observations       = qms09_field('audit_observations', $post_id);

?>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.5;
        }

        h1, h2, h3 {
            color: #1a1a1a;
            margin: 0;
            padding: 0;
        }

        h1 {
            font-size: 18px;
            text-align: center;
            font-weight: bold;
            margin: 10px 0 5px 0;
        }

        h2 {
            font-size: 14px;
            text-align: center;
            margin-bottom: 15px;
        }

        h3 {
            font-size: 12px;
            margin-top: 15px;
            margin-bottom: 8px;
            padding-bottom: 5px;
            border-bottom: 2px solid #4a90e2;
        }

        .section-title {
            background: #e8e8e8;
            font-weight: bold;
            padding: 8px;
            margin-top: 15px;
            border: 1px solid #999;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        th, td {
            border: 1px solid #999;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f2f2f2;
            font-weight: bold;
        }

        .label {
            width: 30%;
            font-weight: bold;
            background: #f9f9f9;
        }

        .finding {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 10px;
            margin: 8px 0;
        }

        .observation {
            background: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 10px;
            margin: 8px 0;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <h1>STAGE 1 AUDIT REPORT</h1>
    <h2>F-09 (QMS Certification)</h2>

    <!-- Audit Details -->
    <div class="section-title">AUDIT INFORMATION</div>
    <table>
        <tr>
            <td class="label">Organization Name</td>
            <td><?= esc_html($org_name) ?></td>
        </tr>
        <tr>
            <td class="label">Reference No.</td>
            <td><?= esc_html($ref_no) ?></td>
        </tr>
        <tr>
            <td class="label">Audit Date</td>
            <td><?= esc_html($audit_date) ?></td>
        </tr>
        <tr>
            <td class="label">Audit Team Members</td>
            <td><?= esc_html($audit_team) ?></td>
        </tr>
    </table>

    <!-- Audit Findings -->
    <h3>Audit Findings</h3>
    <?php if (!empty($findings)) : ?>
        <div class="finding">
            <?= wp_kses_post($findings) ?>
        </div>
    <?php else : ?>
        <div class="finding">
            <p>No findings documented at this time.</p>
        </div>
    <?php endif; ?>

    <!-- Observations -->
    <h3>Audit Observations</h3>
    <?php if (!empty($observations)) : ?>
        <div class="observation">
            <?= wp_kses_post($observations) ?>
        </div>
    <?php else : ?>
        <div class="observation">
            <p>No observations documented at this time.</p>
        </div>
    <?php endif; ?>

    <!-- Summary -->
    <div class="section-title">AUDIT SUMMARY</div>
    <table>
        <tr>
            <th>Item</th>
            <th>Status</th>
        </tr>
        <tr>
            <td>Documentation Review</td>
            <td>Completed</td>
        </tr>
        <tr>
            <td>Non-Conformities Identified</td>
            <td>As detailed above</td>
        </tr>
        <tr>
            <td>Recommendations</td>
            <td>To be addressed per corrective action plan</td>
        </tr>
    </table>

    <!-- Footer -->
    <div style="margin-top: 30px; text-align: center; font-size: 10px; color: #666; page-break-inside: avoid;">
        <hr style="border: none; border-top: 1px solid #ccc; margin: 10px 0;">
        <p>Stage 1 Audit Report - QMS Certification | Generated by GMCSPL</p>
    </div>
</body>
</html>
